version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"     # Tomcat
            - "5005:5005"     # Java Debug
        command: sleep infinity
        volumes:
            - ..:/workspace:cached
            - maven-cache:/home/developer/.m2
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=appdb
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=devpass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    maven-cache:
    mysql-data:
