version: "3.9"
services:
    javaapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"     # Tomcat
            - "5005:5005"     # Java Debug
        volumes:
            - ..:/workspace:cached
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: appdb
            MYSQL_USER: dev
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
